package handler

import (
	"github.com/zeromicro/go-zero/rest"

	"pet/backend/internal/svc"
)

// RegisterHandlers 注册全部路由
func RegisterHandlers(server *rest.Server, sc *svc.ServiceContext) {
	// ───────── 用户端 · 无需登录 ─────────
	server.AddRoutes([]rest.Route{
		{Method: "POST", Path: "/api/auth/wechat/mini-login", Handler: WechatMiniLogin(sc)},
		{Method: "GET", Path: "/api/auth/wechat/h5-url", Handler: WechatH5OAuthURL(sc)},
		{Method: "POST", Path: "/api/auth/wechat/h5-login", Handler: WechatH5Login(sc)},
		{Method: "POST", Path: "/api/auth/sms/send", Handler: SmsSend(sc)},
		{Method: "POST", Path: "/api/auth/sms/login", Handler: SmsLogin(sc)},
		{Method: "POST", Path: "/api/auth/refresh", Handler: RefreshToken(sc)},
		{Method: "GET", Path: "/api/home", Handler: Home(sc)},
		{Method: "GET", Path: "/api/categories", Handler: Categories(sc)},
		{Method: "GET", Path: "/api/breeds", Handler: Breeds(sc)},
		{Method: "GET", Path: "/api/products", Handler: ProductList(sc)},
		{Method: "GET", Path: "/api/products/:id", Handler: ProductDetail(sc)},
		{Method: "GET", Path: "/api/products/:id/related", Handler: RelatedProducts(sc)},
		{Method: "GET", Path: "/api/products/:id/reviews", Handler: ProductReviews(sc)},
		{Method: "GET", Path: "/api/products/:id/review-summary", Handler: ProductReviewSummary(sc)},
		{Method: "GET", Path: "/api/services", Handler: ServiceList(sc)},
		{Method: "GET", Path: "/api/flash-sales", Handler: FlashSales(sc)},
		{Method: "GET", Path: "/api/group-buys", Handler: GroupBuys(sc)},
		{Method: "GET", Path: "/api/bargain-launches", Handler: BargainLaunches(sc)},
		{Method: "POST", Path: "/api/bargain-launches", Handler: BargainLaunch(sc)},
		{Method: "POST", Path: "/api/bargain-help", Handler: BargainHelp(sc)},
		{Method: "GET", Path: "/api/auctions", Handler: Auctions(sc)},
		{Method: "POST", Path: "/api/auctions/:id/deposit", Handler: AuctionDepositPay(sc)},
		{Method: "POST", Path: "/api/auctions/:id/bid", Handler: AuctionBid(sc)},
		{Method: "GET", Path: "/api/tasks", Handler: Tasks(sc)},
		{Method: "POST", Path: "/api/tasks/claim", Handler: TaskClaim(sc)},
		{Method: "POST", Path: "/api/vip/buy", Handler: VipBuy(sc)},
		{Method: "POST", Path: "/api/bookings", Handler: BookingCreate(sc)},
		{Method: "GET", Path: "/api/bookings", Handler: MyBookings(sc)},
		{Method: "POST", Path: "/api/bookings/:no/cancel", Handler: BookingCancel(sc)},
		{Method: "POST", Path: "/api/invoices", Handler: InvoiceApply(sc)},
		{Method: "GET", Path: "/api/insurance-products", Handler: InsuranceList(sc)},
		{Method: "POST", Path: "/api/insurance-apply", Handler: InsuranceApply(sc)},
		{Method: "GET", Path: "/api/stud-services", Handler: StudList(sc)},
		{Method: "GET", Path: "/api/home-config", Handler: HomeConfigGet(sc)},
		{Method: "POST", Path: "/api/distributor/apply", Handler: DistributorApply(sc)},
		{Method: "GET", Path: "/api/distributor/info", Handler: DistributorInfo(sc)},
		{Method: "POST", Path: "/api/distributor/withdraw", Handler: DistributorWithdrawal(sc)},
		{Method: "GET", Path: "/api/invoices", Handler: MyInvoices(sc)},
		{Method: "GET", Path: "/api/trade-config", Handler: TradeConfig(sc)},
		{Method: "GET", Path: "/api/agreement", Handler: Agreement(sc)},
		{Method: "GET", Path: "/api/stores", Handler: StoreList(sc)},
		{Method: "GET", Path: "/api/points-shop", Handler: PointsShop(sc)},
		{Method: "GET", Path: "/api/posts", Handler: PostList(sc)},
		{Method: "GET", Path: "/api/encyclopedia", Handler: EncyclopediaBreeds(sc)},
		{Method: "GET", Path: "/api/encyclopedia/:breedId", Handler: EncyclopediaArticles(sc)},
		{Method: "GET", Path: "/api/search/hot", Handler: SearchHot(sc)},
		{Method: "GET", Path: "/api/search/complete", Handler: SearchComplete(sc)},
		{Method: "POST", Path: "/api/pay/notify/wx", Handler: WxPayNotify(sc)},
	})

	// ───────── 用户端 · 需登录 ─────────
	server.AddRoutes([]rest.Route{
		{Method: "POST", Path: "/api/auth/logout", Handler: Logout(sc)},
		{Method: "GET", Path: "/api/member/profile", Handler: Profile(sc)},
		{Method: "PUT", Path: "/api/member/profile", Handler: UpdateProfile(sc)},
		{Method: "GET", Path: "/api/member/reviews", Handler: MemberReviews(sc)},
		{Method: "POST", Path: "/api/favorites/:id", Handler: Favorite(sc)},
		{Method: "DELETE", Path: "/api/favorites/:id", Handler: Unfavorite(sc)},
		{Method: "GET", Path: "/api/favorites", Handler: FavoriteList(sc)},
		{Method: "POST", Path: "/api/orders", Handler: CreateOrder(sc)},
		{Method: "GET", Path: "/api/orders", Handler: OrderList(sc)},
		{Method: "GET", Path: "/api/orders/:orderNo", Handler: OrderDetail(sc)},
		{Method: "POST", Path: "/api/orders/:orderNo/cancel", Handler: CancelOrder(sc)},
		{Method: "POST", Path: "/api/orders/:orderNo/confirm", Handler: ConfirmOrder(sc)},
		{Method: "POST", Path: "/api/orders/:orderNo/prepay", Handler: Prepay(sc)},
		{Method: "POST", Path: "/api/orders/:orderNo/review", Handler: OrderReview(sc)},
		{Method: "GET", Path: "/api/ship/methods", Handler: ShipMethods(sc)},
		{Method: "GET", Path: "/api/cart", Handler: CartList(sc)},
		{Method: "POST", Path: "/api/cart", Handler: CartAdd(sc)},
		{Method: "PUT", Path: "/api/cart/:id", Handler: CartUpdate(sc)},
		{Method: "DELETE", Path: "/api/cart/:id", Handler: CartDelete(sc)},
		{Method: "DELETE", Path: "/api/cart", Handler: CartDelete(sc)},
		{Method: "GET", Path: "/api/account/delete-status", Handler: AccountDeleteStatus(sc)},
		{Method: "POST", Path: "/api/account/delete-request", Handler: AccountDeleteRequest(sc)},
		{Method: "POST", Path: "/api/account/delete-cancel", Handler: AccountDeleteCancel(sc)},
		{Method: "GET", Path: "/api/points/sign-calendar", Handler: SignCalendar(sc)},
		{Method: "POST", Path: "/api/points/sign-makeup", Handler: SignMakeup(sc)},
		{Method: "POST", Path: "/api/points-shop/:id/exchange", Handler: PointsExchange(sc)},
		{Method: "GET", Path: "/api/points-orders", Handler: MyPointsOrders(sc)},
		{Method: "POST", Path: "/api/posts", Handler: PostCreate(sc)},
		{Method: "POST", Path: "/api/posts/:id/like", Handler: PostLike(sc)},
		{Method: "DELETE", Path: "/api/posts/:id", Handler: PostDelete(sc)},
		{Method: "GET", Path: "/api/my-posts", Handler: MyPosts(sc)},
		{Method: "GET", Path: "/api/pets", Handler: UserPetList(sc)},
		{Method: "POST", Path: "/api/pets", Handler: UserPetUpsert(sc)},
		{Method: "PUT", Path: "/api/pets/:id", Handler: UserPetUpdate(sc)},
		{Method: "DELETE", Path: "/api/pets/:id", Handler: UserPetDelete(sc)},
		{Method: "GET", Path: "/api/payments/:paymentNo/status", Handler: PaymentStatus(sc)},
		{Method: "POST", Path: "/api/aftersale", Handler: AfterSaleApply(sc)},
		{Method: "GET", Path: "/api/aftersale", Handler: AfterSaleByOrder(sc)},
		{Method: "GET", Path: "/api/aftersale/list", Handler: AfterSaleMyList(sc)},
		{Method: "POST", Path: "/api/aftersale/:afterSaleNo/cancel", Handler: AfterSaleCancel(sc)},
		{Method: "GET", Path: "/api/notify/tmpl", Handler: NotifyTmpl(sc)},
		{Method: "GET", Path: "/api/notify/list", Handler: NotifyList(sc)},
		{Method: "POST", Path: "/api/notify/read", Handler: NotifyRead(sc)},
		{Method: "POST", Path: "/api/notify/:id/read", Handler: NotifyReadOne(sc)},
		{Method: "POST", Path: "/api/ai/ask", Handler: AIAsk(sc)},
		{Method: "POST", Path: "/api/ai/recommend", Handler: AIRecommend(sc)},
		{Method: "GET", Path: "/api/coupons", Handler: MyCoupons(sc)},
		{Method: "GET", Path: "/api/coupons/center", Handler: CouponCenter(sc)},
		{Method: "GET", Path: "/api/coupons/usable", Handler: UsableCoupons(sc)},
		{Method: "POST", Path: "/api/coupons/usable", Handler: UsableCoupons(sc)},
		{Method: "POST", Path: "/api/coupons/:id/claim", Handler: ClaimCoupon(sc)},
		{Method: "GET", Path: "/api/ws/cs", Handler: CsWS(sc)},
		{Method: "POST", Path: "/api/cs/messages", Handler: CsMemberSend(sc)},
		{Method: "GET", Path: "/api/cs/messages", Handler: CsMemberMessages(sc)},
		{Method: "POST", Path: "/api/cs/read", Handler: CsMemberRead(sc)},
		{Method: "POST", Path: "/api/upload-token", Handler: MemberUploadToken(sc)},
		{Method: "GET", Path: "/api/addresses", Handler: AddressList(sc)},
		{Method: "POST", Path: "/api/addresses", Handler: AddressSave(sc)},
		{Method: "PUT", Path: "/api/addresses/:id/default", Handler: AddressSetDefault(sc)},
		{Method: "DELETE", Path: "/api/addresses/:id", Handler: AddressDelete(sc)},
		{Method: "POST", Path: "/api/points/signin", Handler: SignIn(sc)},
		{Method: "GET", Path: "/api/points", Handler: MyPoints(sc)},
		{Method: "GET", Path: "/api/invite", Handler: Invite(sc)},
		{Method: "GET", Path: "/api/level", Handler: MyLevel(sc)},
		{Method: "POST", Path: "/api/search/trace", Handler: SearchTrace(sc)},
		{Method: "GET", Path: "/api/search/history", Handler: SearchHistory(sc)},
		{Method: "DELETE", Path: "/api/search/history", Handler: SearchHistoryClear(sc)},
		{Method: "GET", Path: "/api/history/views", Handler: ViewHistory(sc)},
		{Method: "GET", Path: "/api/orders/:orderNo/certificate", Handler: OrderCertificate(sc)},
		{Method: "POST", Path: "/api/orders/:orderNo/mock-pay", Handler: MockPay(sc)},
	})

	// ───────── 平台端 · 登录/刷新（无需 token）─────────
	server.AddRoutes([]rest.Route{
		{Method: "GET", Path: "/api/admin/captcha", Handler: AdminCaptcha(sc)},
		{Method: "POST", Path: "/api/admin/login", Handler: AdminLogin(sc)},
		{Method: "POST", Path: "/api/admin/refresh", Handler: AdminRefresh(sc)},
	})

	// ───────── 平台端 · 需登录 ─────────
	server.AddRoutes([]rest.Route{
		{Method: "POST", Path: "/api/admin/logout", Handler: AdminLogout(sc)},
		{Method: "PUT", Path: "/api/admin/password", Handler: AdminChangePassword(sc)},
		{Method: "GET", Path: "/api/admin/overview", Handler: AdminOverview(sc)},
		{Method: "GET", Path: "/api/admin/report", Handler: AdminReport(sc)},

		{Method: "GET", Path: "/api/admin/flash-sales", Handler: AdminFlashSaleList(sc)},
		{Method: "POST", Path: "/api/admin/flash-sales", Handler: AdminFlashSaleUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/flash-sales/:id", Handler: AdminFlashSaleUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/flash-sales/:id/status", Handler: AdminFlashSaleStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/flash-sales/:id", Handler: AdminFlashSaleDelete(sc)},

		{Method: "GET", Path: "/api/admin/group-buys", Handler: AdminGroupBuyList(sc)},
		{Method: "POST", Path: "/api/admin/group-buys", Handler: AdminGroupBuyUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/group-buys/:id", Handler: AdminGroupBuyUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/group-buys/:id/status", Handler: AdminGroupBuyStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/group-buys/:id", Handler: AdminGroupBuyDelete(sc)},

		{Method: "GET", Path: "/api/admin/audit-logs", Handler: AdminAuditList(sc)},
		{Method: "GET", Path: "/api/admin/sensitive-words", Handler: AdminSensitiveList(sc)},
		{Method: "POST", Path: "/api/admin/sensitive-words", Handler: AdminSensitiveSave(sc)},
		{Method: "PUT", Path: "/api/admin/sensitive-words/:id/status", Handler: AdminSensitiveStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/sensitive-words/:id", Handler: AdminSensitiveDelete(sc)},

		{Method: "POST", Path: "/api/admin/categories", Handler: AdminCategoryUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/categories/:id", Handler: AdminCategoryUpdate(sc)},
		{Method: "DELETE", Path: "/api/admin/categories/:id", Handler: AdminCategoryDelete(sc)},
		{Method: "POST", Path: "/api/admin/breeds", Handler: AdminBreedUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/breeds/:id", Handler: AdminBreedUpdate(sc)},
		{Method: "DELETE", Path: "/api/admin/breeds/:id", Handler: AdminBreedDelete(sc)},

		{Method: "GET", Path: "/api/admin/products", Handler: AdminProductList(sc)},
		{Method: "GET", Path: "/api/admin/products/:id", Handler: AdminProductDetail(sc)},
		{Method: "POST", Path: "/api/admin/products", Handler: AdminProductCreate(sc)},
		{Method: "PUT", Path: "/api/admin/products/:id", Handler: AdminProductUpdate(sc)},
		{Method: "PUT", Path: "/api/admin/products/:id/status", Handler: AdminProductStatus(sc)},
		{Method: "POST", Path: "/api/admin/upload-token", Handler: AdminUploadToken(sc)},

		{Method: "GET", Path: "/api/admin/orders", Handler: AdminOrderList(sc)},
		{Method: "GET", Path: "/api/admin/orders/:orderNo", Handler: AdminOrderDetail(sc)},
		{Method: "POST", Path: "/api/admin/orders/:orderNo/pickup-verify", Handler: AdminPickupVerify(sc)},
		{Method: "POST", Path: "/api/admin/orders/:orderNo/refund", Handler: AdminRefund(sc)},
		{Method: "POST", Path: "/api/admin/orders/:orderNo/ship", Handler: AdminShip(sc)},
		{Method: "POST", Path: "/api/admin/orders/:orderNo/deliver", Handler: AdminDeliver(sc)},

		{Method: "GET", Path: "/api/admin/ship-methods", Handler: AdminShipMethodList(sc)},
		{Method: "POST", Path: "/api/admin/ship-methods", Handler: AdminShipMethodUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/ship-methods/:id", Handler: AdminShipMethodUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/ship-methods/:id/status", Handler: AdminShipMethodStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/ship-methods/:id", Handler: AdminShipMethodDelete(sc)},

		{Method: "GET", Path: "/api/admin/members", Handler: AdminMemberList(sc)},
		{Method: "PUT", Path: "/api/admin/members/:id/status", Handler: AdminMemberStatus(sc)},
		{Method: "PUT", Path: "/api/admin/members/blacklist", Handler: AdminMemberBlacklist(sc)},

		{Method: "GET", Path: "/api/admin/stock-alerts", Handler: AdminStockAlerts(sc)},
		{Method: "POST", Path: "/api/admin/bargain-activities", Handler: AdminBargainUpsert(sc)},
		{Method: "GET", Path: "/api/admin/bargain-activities", Handler: AdminBargainList(sc)},
		{Method: "POST", Path: "/api/admin/auctions", Handler: AdminAuctionUpsert(sc)},
		{Method: "GET", Path: "/api/admin/auctions", Handler: AdminAuctionList(sc)},
		{Method: "GET", Path: "/api/admin/bookings", Handler: AdminBookings(sc)},
		{Method: "POST", Path: "/api/admin/bookings/verify", Handler: AdminBookingVerify(sc)},
		{Method: "GET", Path: "/api/admin/invoices", Handler: AdminInvoices(sc)},
		{Method: "PUT", Path: "/api/admin/invoices/:id/issue", Handler: AdminInvoiceIssue(sc)},
		{Method: "GET", Path: "/api/admin/member-segments", Handler: MemberSegments(sc)},
		{Method: "GET", Path: "/api/admin/member-segments/members", Handler: SegmentMembers(sc)},
		{Method: "POST", Path: "/api/admin/member-segments/issue", Handler: SegmentIssue(sc)},
		{Method: "GET", Path: "/api/admin/price-suggest/:id", Handler: PriceSuggest(sc)},
		{Method: "POST", Path: "/api/admin/insurance-products", Handler: AdminInsuranceUpsert(sc)},
		{Method: "GET", Path: "/api/admin/insurance-applies", Handler: AdminInsuranceApplyList(sc)},
		{Method: "POST", Path: "/api/admin/stud-services", Handler: AdminStudUpsert(sc)},
		{Method: "GET", Path: "/api/admin/home-config", Handler: AdminHomeConfigGet(sc)},
		{Method: "PUT", Path: "/api/admin/home-config", Handler: AdminHomeConfigSet(sc)},
		{Method: "POST", Path: "/api/admin/products/scheduled-off-sale", Handler: ScheduledOffSale(sc)},
		{Method: "GET", Path: "/api/admin/risk-logs", Handler: AdminRiskLogs(sc)},

		{Method: "GET", Path: "/api/admin/finance/payments", Handler: AdminFinancePayments(sc)},
		{Method: "GET", Path: "/api/admin/finance/daily", Handler: AdminFinanceDaily(sc)},
		{Method: "GET", Path: "/api/admin/export/orders", Handler: AdminExportOrders(sc)},
		{Method: "GET", Path: "/api/admin/export/members", Handler: AdminExportMembers(sc)},
		{Method: "GET", Path: "/api/admin/export/points", Handler: AdminExportPoints(sc)},

		{Method: "GET", Path: "/api/admin/suppliers", Handler: AdminSupplierList(sc)},
		{Method: "POST", Path: "/api/admin/suppliers", Handler: AdminSupplierUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/suppliers/:id", Handler: AdminSupplierUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/suppliers/:id/status", Handler: AdminSupplierStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/suppliers/:id", Handler: AdminSupplierDelete(sc)},

		{Method: "GET", Path: "/api/admin/stores", Handler: AdminStoreList(sc)},
		{Method: "POST", Path: "/api/admin/stores", Handler: AdminStoreUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/stores/:id", Handler: AdminStoreUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/stores/:id/status", Handler: AdminStoreStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/stores/:id", Handler: AdminStoreDelete(sc)},

		{Method: "POST", Path: "/api/admin/orders/:orderNo/traces", Handler: AdminTraceAdd(sc)},
		{Method: "POST", Path: "/api/admin/aftersales/:afterSaleNo/return-confirm", Handler: AdminExchangeConfirm(sc)},
		{Method: "GET", Path: "/api/admin/points-products", Handler: AdminPointsProductList(sc)},
		{Method: "POST", Path: "/api/admin/points-products", Handler: AdminPointsProductUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/points-products/:id", Handler: AdminPointsProductUpsert(sc)},
		{Method: "GET", Path: "/api/admin/points-orders", Handler: AdminPointsOrders(sc)},
		{Method: "PUT", Path: "/api/admin/points-orders/:id/ship", Handler: AdminPointsOrderShip(sc)},
		{Method: "GET", Path: "/api/admin/posts", Handler: AdminPostList(sc)},
		{Method: "PUT", Path: "/api/admin/posts/:id/status", Handler: AdminPostStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/posts/:id", Handler: AdminPostDelete(sc)},
		{Method: "GET", Path: "/api/admin/activity-calendar", Handler: AdminActivityCalendar(sc)},
		{Method: "GET", Path: "/api/admin/dashboard/realtime", Handler: AdminRealtime(sc)},

		{Method: "GET", Path: "/api/admin/ai/knowledge", Handler: AdminKnowledgeList(sc)},
		{Method: "POST", Path: "/api/admin/ai/knowledge", Handler: AdminKnowledgeUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/ai/knowledge/:id", Handler: AdminKnowledgeUpsert(sc)},
		{Method: "DELETE", Path: "/api/admin/ai/knowledge/:id", Handler: AdminKnowledgeDelete(sc)},

		{Method: "GET", Path: "/api/admin/marketing/services", Handler: AdminServiceList(sc)},
		{Method: "POST", Path: "/api/admin/marketing/services", Handler: AdminServiceUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/marketing/services/:id", Handler: AdminServiceUpsert(sc)},
		{Method: "DELETE", Path: "/api/admin/marketing/services/:id", Handler: AdminServiceDelete(sc)},

		{Method: "GET", Path: "/api/admin/marketing/coupons", Handler: AdminCouponList(sc)},
		{Method: "POST", Path: "/api/admin/marketing/coupons", Handler: AdminCouponUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/marketing/coupons/:id", Handler: AdminCouponUpsert(sc)},
		{Method: "DELETE", Path: "/api/admin/marketing/coupons/:id", Handler: AdminCouponDelete(sc)},
		{Method: "POST", Path: "/api/admin/marketing/coupons/:id/issue", Handler: AdminCouponIssue(sc)},

		{Method: "GET", Path: "/api/admin/banners", Handler: AdminBannerList(sc)},
		{Method: "POST", Path: "/api/admin/banners", Handler: AdminBannerUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/banners/:id", Handler: AdminBannerUpsert(sc)},
		{Method: "PUT", Path: "/api/admin/banners/:id/status", Handler: AdminBannerStatus(sc)},
		{Method: "DELETE", Path: "/api/admin/banners/:id", Handler: AdminBannerDelete(sc)},

		{Method: "GET", Path: "/api/admin/cs/sessions", Handler: AdminCsSessions(sc)},
		{Method: "GET", Path: "/api/admin/cs/sessions/:id/messages", Handler: AdminCsMessages(sc)},
		{Method: "POST", Path: "/api/admin/cs/sessions/:id/messages", Handler: AdminCsMessages(sc)},
		{Method: "POST", Path: "/api/admin/cs/sessions/:id/read", Handler: AdminCsRead(sc)},
		{Method: "POST", Path: "/api/admin/cs/sessions/:id/close", Handler: AdminCsClose(sc)},

		{Method: "GET", Path: "/api/admin/reviews", Handler: AdminReviews(sc)},
		{Method: "PUT", Path: "/api/admin/reviews/:id/status", Handler: AdminReviewStatus(sc)},
		{Method: "POST", Path: "/api/admin/reviews/:id/reply", Handler: AdminReviewReply(sc)},
		{Method: "DELETE", Path: "/api/admin/reviews/:id", Handler: AdminReviewDelete(sc)},
		{Method: "GET", Path: "/api/admin/aftersales", Handler: AdminAfterSales(sc)},
		{Method: "POST", Path: "/api/admin/aftersales/:afterSaleNo/audit", Handler: AdminAfterSaleAudit(sc)},
	})
}
