export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/detail/index',
    'pages/list/index',
    'pages/me/index',
    'pages/my-reviews/index',
    'pages/my-aftersales/index',
    'pages/ai-chat/index',
    'pages/recommend/index',
    'pages/service-chat/index',
    'pages/checkout/index',
    'pages/orders/index',
    'pages/order-detail/index',
    'pages/order-review/index',
    'pages/after-sale/index',
    'pages/notify/index',
    'pages/coupon-center/index',
    'pages/favorites/index',
    'pages/points/index',
    'pages/invite/index',
    'pages/address/index',
    'pages/cart/index',
    'pages/pet/index',
    'pages/agreement/index',
    'pages/square/index',
    'pages/shop/index',
    'pages/encyclopedia/index',
    'pages/tasks/index',
    'pages/vip/index',
    'pages/bargain/index',
    'pages/auction/index',
    'pages/booking/index',
    'pages/insurance/index',
    'pages/stud/index',
    'pages/invoices/index',
    'pages/login/index',
    'pages/certificate/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '宠物之家',
    navigationBarTextStyle: 'black',
  },
})


